# 洲际地图
V5Front_ResGArea = [
    {
        "key": "00",
        "_parent": "0",
        "_name": "北美洲"
    }, {
        "key": "01",
        "_parent": "0",
        "_name": "中美洲"
    }, {
        "key": "02",
        "_parent": "0",
        "_name": "加勒比地区"
    }, {
        "key": "03",
        "_parent": "0",
        "_name": "南美洲"
    }, {
        "key": "11",
        "_parent": "1",
        "_name": "东欧"
    }, {
        "key": "12",
        "_parent": "1",
        "_name": "南欧"
    }, {
        "key": "13",
        "_parent": "1",
        "_name": "西欧"
    }, {
        "key": "14",
        "_parent": "1",
        "_name": "北欧"
    }, {
        "key": "21",
        "_parent": "2",
        "_name": "东亚"
    }, {
        "key": "22",
        "_parent": "2",
        "_name": "南亚"
    }, {
        "key": "23",
        "_parent": "2",
        "_name": "东南亚"
    }, {
        "key": "24",
        "_parent": "2",
        "_name": "中亚"
    }, {
        "key": "25",
        "_parent": "2",
        "_name": "西亚"
    }, {
        "key": "31",
        "_parent": "3",
        "_name": "东非"
    }, {
        "key": "32",
        "_parent": "3",
        "_name": "南非"
    }, {
        "key": "33",
        "_parent": "3",
        "_name": "中非"
    }, {
        "key": "34",
        "_parent": "3",
        "_name": "西非"
    }, {
        "key": "35",
        "_parent": "3",
        "_name": "北非"
    }, {
        "key": "41",
        "_parent": "4",
        "_name": "大洋洲"
    }, {
        "key": "51",
        "_parent": "5",
        "_name": "其它"
    }]

# 地区地图
V5Front_ResGCountry = [
    {
        "key": "0",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Albania",
        "_firstCode": "A",
        "_mnemonic": "AEBNY",
        "_name": "未知"
    },
    {
        "key": "0103",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Albania",
        "_firstCode": "A",
        "_mnemonic": "AEBNY",
        "_name": "阿尔巴尼亚"
    }, {
        "key": "0104",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Algeria",
        "_firstCode": "A",
        "_mnemonic": "AEJLY",
        "_name": "阿尔及利亚"
    }, {
        "key": "0102",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Afghanistan",
        "_firstCode": "A",
        "_mnemonic": "AFH",
        "_name": "阿富汗"
    }, {
        "key": "0112",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Argentina",
        "_firstCode": "A",
        "_mnemonic": "AGT",
        "_name": "阿根廷"
    }, {
        "key": "0503",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "United Arab Emirates",
        "_firstCode": "A",
        "_mnemonic": "ALQ",
        "_name": "阿联酋"
    }, {
        "key": "9203",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "",
        "_firstCode": "A",
        "_mnemonic": "ALB",
        "_name": "阿鲁巴 [NL]"
    }, {
        "key": "1501",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Oman",
        "_firstCode": "A",
        "_mnemonic": "AM",
        "_name": "阿曼"
    }, {
        "key": "0117",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Azerbaijan",
        "_firstCode": "A",
        "_mnemonic": "ASBJ",
        "_name": "阿塞拜疆"
    }, {
        "key": "9003",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "",
        "_firstCode": "A",
        "_mnemonic": "ASSD",
        "_name": "阿森松岛 [GB]"
    }, {
        "key": "0502",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Egypt",
        "_firstCode": "A",
        "_mnemonic": "AJ",
        "_name": "埃及"
    }, {
        "key": "0505",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Ethiopia",
        "_firstCode": "A",
        "_mnemonic": "ASEBY",
        "_name": "埃塞俄比亚"
    }, {
        "key": "0905",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Ireland",
        "_firstCode": "A",
        "_mnemonic": "AEL",
        "_name": "爱尔兰"
    }, {
        "key": "0504",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Estonia",
        "_firstCode": "A",
        "_mnemonic": "ASNY",
        "_name": "爱沙尼亚"
    }, {
        "key": "0105",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Andorra",
        "_firstCode": "A",
        "_mnemonic": "ADE",
        "_name": "安道尔"
    }, {
        "key": "0106",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Angola",
        "_firstCode": "A",
        "_mnemonic": "AGL",
        "_name": "安哥拉"
    }, {
        "key": "9002",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "",
        "_firstCode": "A",
        "_mnemonic": "AGL",
        "_name": "安圭拉 [GB]"
    }, {
        "key": "0110",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Antigua and Barb.",
        "_firstCode": "A",
        "_mnemonic": "ADGHBBD",
        "_name": "安提瓜和巴布达"
    }, {
        "key": "0116",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Austria",
        "_firstCode": "A",
        "_mnemonic": "ADL",
        "_name": "奥地利"
    }, {
        "key": "9102",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Aland",
        "_firstCode": "A",
        "_mnemonic": "ALQD",
        "_name": "奥兰群岛 [FI]"
    }, {
        "key": "0115",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Australia",
        "_firstCode": "A",
        "_mnemonic": "ADLY",
        "_name": "澳大利亚"
    }, {
        "key": "1301",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "",
        "_firstCode": "A",
        "_mnemonic": "AM",
        "_name": "澳门 [CN]"
    }, {
        "key": "0204",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Barbados",
        "_firstCode": "B",
        "_mnemonic": "BBDS",
        "_name": "巴巴多斯"
    }, {
        "key": "1604",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Papua New Guinea",
        "_firstCode": "B",
        "_mnemonic": "BBYXJNY",
        "_name": "巴布亚新几内亚"
    }, {
        "key": "0201",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Bahamas",
        "_firstCode": "B",
        "_mnemonic": "BHM",
        "_name": "巴哈马"
    }, {
        "key": "1601",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Pakistan",
        "_firstCode": "B",
        "_mnemonic": "BJST",
        "_name": "巴基斯坦"
    }, {
        "key": "1605",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Paraguay",
        "_firstCode": "B",
        "_mnemonic": "BLG",
        "_name": "巴拉圭"
    }, {
        "key": "1602",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Palestine",
        "_firstCode": "B",
        "_mnemonic": "BLST",
        "_name": "巴勒斯坦"
    }, {
        "key": "0202",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Bahrain",
        "_firstCode": "B",
        "_mnemonic": "BL",
        "_name": "巴林"
    }, {
        "key": "1603",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Panama",
        "_firstCode": "B",
        "_mnemonic": "BNM",
        "_name": "巴拿马"
    }, {
        "key": "0215",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Brazil",
        "_firstCode": "B",
        "_mnemonic": "BX",
        "_name": "巴西"
    }, {
        "key": "0205",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Belarus",
        "_firstCode": "B",
        "_mnemonic": "BELS",
        "_name": "白俄罗斯"
    }, {
        "key": "9004",
        "_gArea": "00",
        "_gContinent": "0",
        "_nameGeo": "Bermuda",
        "_firstCode": "B",
        "_mnemonic": "BMD",
        "_name": "百慕大 [GB]"
    }, {
        "key": "0217",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Bulgaria",
        "_firstCode": "B",
        "_mnemonic": "BJLY",
        "_name": "保加利亚"
    }, {
        "key": "0208",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Benin",
        "_firstCode": "B",
        "_mnemonic": "BN",
        "_name": "贝宁"
    }, {
        "key": "0206",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Belgium",
        "_firstCode": "B",
        "_mnemonic": "BLS",
        "_name": "比利时"
    }, {
        "key": "0901",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Iceland",
        "_firstCode": "B",
        "_mnemonic": "BD",
        "_name": "冰岛"
    }, {
        "key": "0212",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Bosnia and Herz.",
        "_firstCode": "B",
        "_mnemonic": "BH",
        "_name": "波黑"
    }, {
        "key": "1608",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Poland",
        "_firstCode": "B",
        "_mnemonic": "BL",
        "_name": "波兰"
    }, {
        "key": "0211",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Bolivia",
        "_firstCode": "B",
        "_mnemonic": "BLWY",
        "_name": "玻利维亚"
    }, {
        "key": "0207",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Belize",
        "_firstCode": "B",
        "_mnemonic": "BLC",
        "_name": "伯利兹"
    }, {
        "key": "0213",
        "_gArea": "32",
        "_gContinent": "3",
        "_nameGeo": "Botswana",
        "_firstCode": "B",
        "_mnemonic": "BCWN",
        "_name": "博茨瓦纳"
    }, {
        "key": "0210",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Bhutan",
        "_firstCode": "B",
        "_mnemonic": "BD",
        "_name": "不丹"
    }, {
        "key": "0218",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Burkina Faso",
        "_firstCode": "B",
        "_mnemonic": "BJNFS",
        "_name": "布基纳法索"
    }, {
        "key": "0219",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Burundi",
        "_firstCode": "B",
        "_mnemonic": "BLD",
        "_name": "布隆迪"
    }, {
        "key": "1606",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Peru",
        "_firstCode": "B",
        "_mnemonic": "BL",
        "_name": "秘鲁"
    }, {
        "key": "1106",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "Dem. Rep. Korea",
        "_firstCode": "C",
        "_mnemonic": "CX",
        "_name": "朝鲜"
    }, {
        "key": "0507",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Eq. Guinea",
        "_firstCode": "C",
        "_mnemonic": "CDJNY",
        "_name": "赤道几内亚"
    }, {
        "key": "0401",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Denmark",
        "_firstCode": "D",
        "_mnemonic": "DM",
        "_name": "丹麦"
    }, {
        "key": "0704",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Germany",
        "_firstCode": "D",
        "_mnemonic": "DG",
        "_name": "德国"
    }, {
        "key": "0508",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Timor-Leste",
        "_firstCode": "D",
        "_mnemonic": "DDW",
        "_name": "东帝汶"
    }, {
        "key": "2005",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Togo",
        "_firstCode": "D",
        "_mnemonic": "DG",
        "_name": "多哥"
    }, {
        "key": "0404",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Dominican Rep.",
        "_firstCode": "D",
        "_mnemonic": "DMNJ",
        "_name": "多米尼加"
    }, {
        "key": "0403",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Dominica",
        "_firstCode": "D",
        "_mnemonic": "DMNK",
        "_name": "多米尼克"
    }, {
        "key": "1803",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Russia",
        "_firstCode": "E",
        "_mnemonic": "ELS",
        "_name": "俄罗斯联邦"
    }, {
        "key": "0501",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Ecuador",
        "_firstCode": "E",
        "_mnemonic": "EGDE",
        "_name": "厄瓜多尔"
    }, {
        "key": "0506",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Eritrea",
        "_firstCode": "E",
        "_mnemonic": "ELTLY",
        "_name": "厄立特里亚"
    }, {
        "key": "0605",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "France",
        "_firstCode": "F",
        "_mnemonic": "FG",
        "_name": "法国"
    }, {
        "key": "9602",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "F",
        "_mnemonic": "FLQD",
        "_name": "法罗群岛 [DK]"
    }, {
        "key": "2205",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "F",
        "_mnemonic": "FDG",
        "_name": "梵蒂冈"
    }, {
        "key": "1607",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Philippines",
        "_firstCode": "F",
        "_mnemonic": "FLB",
        "_name": "菲律宾"
    }, {
        "key": "0603",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Fiji",
        "_firstCode": "F",
        "_mnemonic": "FJ",
        "_name": "斐济"
    }, {
        "key": "0604",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Finland",
        "_firstCode": "F",
        "_mnemonic": "FL",
        "_name": "芬兰"
    }, {
        "key": "0306",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Cape Verde",
        "_firstCode": "F",
        "_mnemonic": "FDJ",
        "_name": "佛得角"
    }, {
        "key": "0702",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Gambia",
        "_firstCode": "G",
        "_mnemonic": "GBY",
        "_name": "冈比亚"
    }, {
        "key": "0315",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Congo",
        "_firstCode": "G",
        "_mnemonic": "GGGHG",
        "_name": "刚果共和国"
    }, {
        "key": "0316",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Dem. Rep. Congo",
        "_firstCode": "G",
        "_mnemonic": "GGMZGHG",
        "_name": "刚果民主共和国"
    }, {
        "key": "0313",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Colombia",
        "_firstCode": "G",
        "_mnemonic": "GLBY",
        "_name": "哥伦比亚"
    }, {
        "key": "0318",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Costa Rica",
        "_firstCode": "G",
        "_mnemonic": "GSDLJ",
        "_name": "哥斯达黎加"
    }, {
        "key": "0709",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Grenada",
        "_firstCode": "G",
        "_mnemonic": "GLND",
        "_name": "格林纳达 [GB]"
    }, {
        "key": "9603",
        "_gArea": "00",
        "_gContinent": "0",
        "_nameGeo": "Greenland",
        "_firstCode": "G",
        "_mnemonic": "GLL",
        "_name": "格陵兰 [DK]"
    }, {
        "key": "0703",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Georgia",
        "_firstCode": "G",
        "_mnemonic": "GLJY",
        "_name": "格鲁吉亚"
    }, {
        "key": "9007",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "G",
        "_mnemonic": "GXD",
        "_name": "根西岛 [GB]"
    }, {
        "key": "0320",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Cuba",
        "_firstCode": "G",
        "_mnemonic": "GB",
        "_name": "古巴"
    }, {
        "key": "0714",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Guyana",
        "_firstCode": "G",
        "_mnemonic": "GYN",
        "_name": "圭亚那"
    }, {
        "key": "1101",
        "_gArea": "24",
        "_gContinent": "2",
        "_nameGeo": "Kazakhstan",
        "_firstCode": "H",
        "_mnemonic": "HSKST",
        "_name": "哈萨克斯坦"
    }, {
        "key": "0802",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Haiti",
        "_firstCode": "H",
        "_mnemonic": "HD",
        "_name": "海地"
    }, {
        "key": "9501",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "ADLYHWLD",
        "_name": "海外领地 [AU]"
    }, {
        "key": "9601",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "DMHWLD",
        "_name": "海外领地 [DK]"
    }, {
        "key": "8901",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "XBYHWLD",
        "_name": "海外领地 [ES]"
    }, {
        "key": "9101",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "FLHWLD",
        "_name": "海外领地 [FI]"
    }, {
        "key": "9701",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "FGHWLD",
        "_name": "海外领地 [FR]"
    }, {
        "key": "9001",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "YGHWLD",
        "_name": "海外领地 [GB]"
    }, {
        "key": "9201",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "HLHWLD",
        "_name": "海外领地 [NL]"
    }, {
        "key": "9401",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "NWHWLD",
        "_name": "海外领地 [NO]"
    }, {
        "key": "9901",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "XXLHWLD",
        "_name": "海外领地 [NZ]"
    }, {
        "key": "9301",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "PTYHWLD",
        "_name": "海外领地 [PT]"
    }, {
        "key": "9801",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "MGHWLD",
        "_name": "海外领地 [US]"
    }, {
        "key": "1105",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "Korea",
        "_firstCode": "H",
        "_mnemonic": "HG",
        "_name": "韩国"
    }, {
        "key": "1404",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Netherlands",
        "_firstCode": "H",
        "_mnemonic": "HL",
        "_name": "荷兰"
    }, {
        "key": "9202",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "",
        "_firstCode": "H",
        "_mnemonic": "HSADLS",
        "_name": "荷属安的列斯 [NL]"
    }, {
        "key": "1319",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Montenegro",
        "_firstCode": "H",
        "_mnemonic": "HS",
        "_name": "黑山"
    }, {
        "key": "0804",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Honduras",
        "_firstCode": "H",
        "_mnemonic": "HDLS",
        "_name": "洪都拉斯"
    }, {
        "key": "1104",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Kiribati",
        "_firstCode": "J",
        "_mnemonic": "JLBS",
        "_name": "基里巴斯"
    }, {
        "key": "0402",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Djibouti",
        "_firstCode": "J",
        "_mnemonic": "JBD",
        "_name": "吉布提"
    }, {
        "key": "1109",
        "_gArea": "24",
        "_gContinent": "2",
        "_nameGeo": "Kyrgyzstan",
        "_firstCode": "J",
        "_mnemonic": "JEJSST",
        "_name": "吉尔吉斯斯坦"
    }, {
        "key": "0716",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Guinea-Bissau",
        "_firstCode": "J",
        "_mnemonic": "JNYBS",
        "_name": "几内亚比绍"
    }, {
        "key": "0713",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Guinea",
        "_firstCode": "J",
        "_mnemonic": "JNYGHG",
        "_name": "几内亚共和国"
    }, {
        "key": "0304",
        "_gArea": "00",
        "_gContinent": "0",
        "_nameGeo": "Canada",
        "_firstCode": "J",
        "_mnemonic": "JND",
        "_name": "加拿大"
    }, {
        "key": "0705",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Ghana",
        "_firstCode": "J",
        "_mnemonic": "JN",
        "_name": "加纳"
    }, {
        "key": "0701",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Gabon",
        "_firstCode": "J",
        "_mnemonic": "JP",
        "_name": "加蓬"
    }, {
        "key": "0302",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Cambodia",
        "_firstCode": "J",
        "_mnemonic": "JBZ",
        "_name": "柬埔寨"
    }, {
        "key": "0322",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Czech Rep.",
        "_firstCode": "J",
        "_mnemonic": "JK",
        "_name": "捷克"
    }, {
        "key": "2602",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Zimbabwe",
        "_firstCode": "J",
        "_mnemonic": "JBBW",
        "_name": "津巴布韦"
    }, {
        "key": "0303",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Cameroon",
        "_firstCode": "K",
        "_mnemonic": "KML",
        "_name": "喀麦隆"
    }, {
        "key": "1701",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Qatar",
        "_firstCode": "K",
        "_mnemonic": "KTE",
        "_name": "卡塔尔"
    }, {
        "key": "9005",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Cayman Is.",
        "_firstCode": "K",
        "_mnemonic": "KMQD",
        "_name": "开曼群岛 [GB]"
    }, {
        "key": "0314",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Comoros",
        "_firstCode": "K",
        "_mnemonic": "KML",
        "_name": "科摩罗"
    }, {
        "key": "1107",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "K",
        "_mnemonic": "KSW",
        "_name": "科索沃"
    }, {
        "key": "0312",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Côte d'Ivoire",
        "_firstCode": "K",
        "_mnemonic": "KTDW",
        "_name": "科特迪瓦"
    }, {
        "key": "1108",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Kuwait",
        "_firstCode": "K",
        "_mnemonic": "KWT",
        "_name": "科威特"
    }, {
        "key": "0319",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Croatia",
        "_firstCode": "K",
        "_mnemonic": "KLDY",
        "_name": "克罗地亚"
    }, {
        "key": "1102",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Kenya",
        "_firstCode": "K",
        "_mnemonic": "KNY",
        "_name": "肯尼亚"
    }, {
        "key": "0317",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "",
        "_firstCode": "K",
        "_mnemonic": "KKQD",
        "_name": "库克群岛 [NZ]"
    }, {
        "key": "1202",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Latvia",
        "_firstCode": "L",
        "_mnemonic": "LTWY",
        "_name": "拉脱维亚"
    }, {
        "key": "1204",
        "_gArea": "32",
        "_gContinent": "3",
        "_nameGeo": "Lesotho",
        "_firstCode": "L",
        "_mnemonic": "LST",
        "_name": "莱索托"
    }, {
        "key": "1201",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Lao PDR",
        "_firstCode": "L",
        "_mnemonic": "LW",
        "_name": "老挝"
    }, {
        "key": "1203",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Lebanon",
        "_firstCode": "L",
        "_mnemonic": "LBN",
        "_name": "黎巴嫩"
    }, {
        "key": "1208",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Lithuania",
        "_firstCode": "L",
        "_mnemonic": "LTW",
        "_name": "立陶宛"
    }, {
        "key": "1205",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Liberia",
        "_firstCode": "L",
        "_mnemonic": "LBLY",
        "_name": "利比里亚"
    }, {
        "key": "1206",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Libya",
        "_firstCode": "L",
        "_mnemonic": "LBY",
        "_name": "利比亚"
    }, {
        "key": "1207",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Liechtenstein",
        "_firstCode": "L",
        "_mnemonic": "LZDSD",
        "_name": "列支敦士登"
    }, {
        "key": "1210",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Luxembourg",
        "_firstCode": "L",
        "_mnemonic": "LSB",
        "_name": "卢森堡"
    }, {
        "key": "1804",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Rwanda",
        "_firstCode": "L",
        "_mnemonic": "LWD",
        "_name": "卢旺达"
    }, {
        "key": "1802",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Romania",
        "_firstCode": "L",
        "_mnemonic": "LMNY",
        "_name": "罗马尼亚"
    }, {
        "key": "1303",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Madagascar",
        "_firstCode": "M",
        "_mnemonic": "MDJSJ",
        "_name": "马达加斯加"
    }, {
        "key": "1306",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "",
        "_firstCode": "M",
        "_mnemonic": "MEDF",
        "_name": "马尔代夫"
    }, {
        "key": "1308",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Malta",
        "_firstCode": "M",
        "_mnemonic": "MET",
        "_name": "马耳他"
    }, {
        "key": "1304",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Malawi",
        "_firstCode": "M",
        "_mnemonic": "MLW",
        "_name": "马拉维"
    }, {
        "key": "1305",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Malaysia",
        "_firstCode": "M",
        "_mnemonic": "MLXY",
        "_name": "马来西亚"
    }, {
        "key": "1307",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Mali",
        "_firstCode": "M",
        "_mnemonic": "MLGHG",
        "_name": "马里共和国"
    }, {
        "key": "1302",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Macedonia",
        "_firstCode": "M",
        "_mnemonic": "MJD",
        "_name": "马其顿"
    }, {
        "key": "1310",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "",
        "_firstCode": "M",
        "_mnemonic": "MSEQD",
        "_name": "马绍尔群岛"
    }, {
        "key": "1313",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Mauritius",
        "_firstCode": "M",
        "_mnemonic": "MLQS",
        "_name": "毛里求斯"
    }, {
        "key": "1312",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Mauritania",
        "_firstCode": "M",
        "_mnemonic": "MLDNY",
        "_name": "毛里塔尼亚"
    }, {
        "key": "2105",
        "_gArea": "00",
        "_gContinent": "0",
        "_nameGeo": "United States",
        "_firstCode": "M",
        "_mnemonic": "MG",
        "_name": "美国"
    }, {
        "key": "1318",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "Mongolia",
        "_firstCode": "M",
        "_mnemonic": "MGG",
        "_name": "蒙古国"
    }, {
        "key": "0203",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Bangladesh",
        "_firstCode": "M",
        "_mnemonic": "MJLG",
        "_name": "孟加拉国"
    }, {
        "key": "1315",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Micronesia",
        "_firstCode": "M",
        "_mnemonic": "MKLNXYLB",
        "_name": "密克罗尼西亚联邦"
    }, {
        "key": "1323",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Myanmar",
        "_firstCode": "M",
        "_mnemonic": "MD",
        "_name": "缅甸"
    }, {
        "key": "1316",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Moldova",
        "_firstCode": "M",
        "_mnemonic": "MEDW",
        "_name": "摩尔多瓦"
    }, {
        "key": "1321",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Morocco",
        "_firstCode": "M",
        "_mnemonic": "MLG",
        "_name": "摩洛哥"
    }, {
        "key": "1317",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "M",
        "_mnemonic": "MNG",
        "_name": "摩纳哥"
    }, {
        "key": "1322",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Mozambique",
        "_firstCode": "M",
        "_mnemonic": "MSBK",
        "_name": "莫桑比克"
    }, {
        "key": "1314",
        "_gArea": "00",
        "_gContinent": "0",
        "_nameGeo": "Mexico",
        "_firstCode": "M",
        "_mnemonic": "MXG",
        "_name": "墨西哥"
    }, {
        "key": "1401",
        "_gArea": "32",
        "_gContinent": "3",
        "_nameGeo": "Namibia",
        "_firstCode": "N",
        "_mnemonic": "NMBY",
        "_name": "纳米比亚"
    }, {
        "key": "1932",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "N",
        "_mnemonic": "NAST",
        "_name": "南奥塞梯"
    }, {
        "key": "1917",
        "_gArea": "32",
        "_gContinent": "3",
        "_nameGeo": "South Africa",
        "_firstCode": "N",
        "_mnemonic": "NF",
        "_name": "南非"
    }, {
        "key": "0108",
        "_gArea": "51",
        "_gContinent": "5",
        "_nameGeo": "",
        "_firstCode": "N",
        "_mnemonic": "NJZ",
        "_name": "南极洲"
    }, {
        "key": "1402",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "",
        "_firstCode": "N",
        "_mnemonic": "NL",
        "_name": "瑙鲁"
    }, {
        "key": "1403",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Nepal",
        "_firstCode": "N",
        "_mnemonic": "NBE",
        "_name": "尼泊尔"
    }, {
        "key": "1407",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Nicaragua",
        "_firstCode": "N",
        "_mnemonic": "NJLG",
        "_name": "尼加拉瓜"
    }, {
        "key": "1409",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Niger",
        "_firstCode": "N",
        "_mnemonic": "NRE",
        "_name": "尼日尔"
    }, {
        "key": "1410",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Nigeria",
        "_firstCode": "N",
        "_mnemonic": "NRLY",
        "_name": "尼日利亚"
    }, {
        "key": "1408",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Norway",
        "_firstCode": "N",
        "_mnemonic": "NW",
        "_name": "挪威"
    }, {
        "key": "9502",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "",
        "_firstCode": "N",
        "_mnemonic": "NFKD",
        "_name": "诺福克岛 [AU]"
    }, {
        "key": "1614",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Palau",
        "_firstCode": "P",
        "_mnemonic": "PL",
        "_name": "帕劳"
    }, {
        "key": "1610",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Portugal",
        "_firstCode": "P",
        "_mnemonic": "PTY",
        "_name": "葡萄牙"
    }, {
        "key": "1002",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "Japan",
        "_firstCode": "R",
        "_mnemonic": "RB",
        "_name": "日本"
    }, {
        "key": "1924",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Sweden",
        "_firstCode": "R",
        "_mnemonic": "RD",
        "_name": "瑞典"
    }, {
        "key": "1925",
        "_gArea": "13",
        "_gContinent": "1",
        "_nameGeo": "Switzerland",
        "_firstCode": "R",
        "_mnemonic": "RS",
        "_name": "瑞士"
    }, {
        "key": "1903",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "El Salvador",
        "_firstCode": "S",
        "_mnemonic": "SEWD",
        "_name": "萨尔瓦多"
    }, {
        "key": "1909",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Serbia",
        "_firstCode": "S",
        "_mnemonic": "SEWY",
        "_name": "塞尔维亚"
    }, {
        "key": "1912",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Sierra Leone",
        "_firstCode": "S",
        "_mnemonic": "SLLA",
        "_name": "塞拉利昂"
    }, {
        "key": "1908",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Senegal",
        "_firstCode": "S",
        "_mnemonic": "SNJE",
        "_name": "塞内加尔"
    }, {
        "key": "0321",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Cyprus",
        "_firstCode": "S",
        "_mnemonic": "SPLS",
        "_name": "塞浦路斯"
    }, {
        "key": "1911",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Seychelles",
        "_firstCode": "S",
        "_mnemonic": "SSE",
        "_name": "塞舌尔"
    }, {
        "key": "1907",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Saudi Arabia",
        "_firstCode": "S",
        "_mnemonic": "STALB",
        "_name": "沙特阿拉伯"
    }, {
        "key": "1906",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "São Tomé and Principe",
        "_firstCode": "S",
        "_mnemonic": "SDMHPLXB",
        "_name": "圣多美和普林西比"
    }, {
        "key": "9008",
        "_gArea": "34",
        "_gContinent": "3",
        "_nameGeo": "Saint Helena",
        "_firstCode": "S",
        "_mnemonic": "SHLND",
        "_name": "圣赫勒拿岛 [GB]"
    }, {
        "key": "1927",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "",
        "_firstCode": "S",
        "_mnemonic": "SJCHNWS",
        "_name": "圣基茨和尼维斯"
    }, {
        "key": "1209",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Saint Lucia",
        "_firstCode": "S",
        "_mnemonic": "SLXY",
        "_name": "圣卢西亚"
    }, {
        "key": "1905",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "S",
        "_mnemonic": "SMLN",
        "_name": "圣马力诺"
    }, {
        "key": "1902",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "St. Vin. and Gren.",
        "_firstCode": "S",
        "_mnemonic": "SWSTHGLNDS",
        "_name": "圣文森特和格林纳丁斯"
    }, {
        "key": "1919",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Sri Lanka",
        "_firstCode": "S",
        "_mnemonic": "SLLK",
        "_name": "斯里兰卡"
    }, {
        "key": "1914",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Slovakia",
        "_firstCode": "S",
        "_mnemonic": "SLFK",
        "_name": "斯洛伐克"
    }, {
        "key": "1915",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Slovenia",
        "_firstCode": "S",
        "_mnemonic": "SLWNY",
        "_name": "斯洛文尼亚"
    }, {
        "key": "1923",
        "_gArea": "32",
        "_gContinent": "3",
        "_nameGeo": "Swaziland",
        "_firstCode": "S",
        "_mnemonic": "SWSL",
        "_name": "斯威士兰"
    }, {
        "key": "1920",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Sudan",
        "_firstCode": "S",
        "_mnemonic": "SD",
        "_name": "苏丹"
    }, {
        "key": "1930",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "S",
        "_mnemonic": "SGL",
        "_name": "苏格兰"
    }, {
        "key": "1921",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Suriname",
        "_firstCode": "S",
        "_mnemonic": "SLN",
        "_name": "苏里南"
    }, {
        "key": "1916",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Solomon Is.",
        "_firstCode": "S",
        "_mnemonic": "SLMQD",
        "_name": "所罗门群岛"
    }, {
        "key": "1929",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Somalia",
        "_firstCode": "S",
        "_mnemonic": "SML",
        "_name": "索马里"
    }, {
        "key": "2002",
        "_gArea": "24",
        "_gContinent": "2",
        "_nameGeo": "Tajikistan",
        "_firstCode": "T",
        "_mnemonic": "TJKST",
        "_name": "塔吉克斯坦"
    }, {
        "key": "2001",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "",
        "_firstCode": "T",
        "_mnemonic": "TW",
        "_name": "台湾 [CN]"
    }, {
        "key": "2004",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Thailand",
        "_firstCode": "T",
        "_mnemonic": "TG",
        "_name": "泰国"
    }, {
        "key": "2003",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Tanzania",
        "_firstCode": "T",
        "_mnemonic": "TSNY",
        "_name": "坦桑尼亚"
    }, {
        "key": "2006",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Tonga",
        "_firstCode": "T",
        "_mnemonic": "TJ",
        "_name": "汤加"
    }, {
        "key": "2007",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Trinidad and Tobago",
        "_firstCode": "T",
        "_mnemonic": "TLNDHDBG",
        "_name": "特立尼达和多巴哥"
    }, {
        "key": "2010",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "Tunisia",
        "_firstCode": "T",
        "_mnemonic": "TNS",
        "_name": "突尼斯"
    }, {
        "key": "2009",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "",
        "_firstCode": "T",
        "_mnemonic": "TWL",
        "_name": "图瓦卢"
    }, {
        "key": "2011",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Turkey",
        "_firstCode": "T",
        "_mnemonic": "TEJ",
        "_name": "土耳其"
    }, {
        "key": "2012",
        "_gArea": "24",
        "_gContinent": "2",
        "_nameGeo": "Turkmenistan",
        "_firstCode": "T",
        "_mnemonic": "TKMST",
        "_name": "土库曼斯坦"
    }, {
        "key": "2202",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Vanuatu",
        "_firstCode": "W",
        "_mnemonic": "WNAT",
        "_name": "瓦努阿图"
    }, {
        "key": "0712",
        "_gArea": "01",
        "_gContinent": "0",
        "_nameGeo": "Guatemala",
        "_firstCode": "W",
        "_mnemonic": "WDML",
        "_name": "危地马拉"
    }, {
        "key": "2203",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Venezuela",
        "_firstCode": "W",
        "_mnemonic": "WNRL",
        "_name": "委内瑞拉"
    }, {
        "key": "0216",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Brunei",
        "_firstCode": "W",
        "_mnemonic": "WL",
        "_name": "文莱"
    }, {
        "key": "2101",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Uganda",
        "_firstCode": "W",
        "_mnemonic": "WGD",
        "_name": "乌干达"
    }, {
        "key": "2102",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Ukraine",
        "_firstCode": "W",
        "_mnemonic": "WKL",
        "_name": "乌克兰"
    }, {
        "key": "2104",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Uruguay",
        "_firstCode": "W",
        "_mnemonic": "WLG",
        "_name": "乌拉圭"
    }, {
        "key": "2103",
        "_gArea": "24",
        "_gContinent": "2",
        "_nameGeo": "Uzbekistan",
        "_firstCode": "W",
        "_mnemonic": "WCBKST",
        "_name": "乌兹别克斯坦"
    }, {
        "key": "1928",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "Samoa",
        "_firstCode": "X",
        "_mnemonic": "XSMY",
        "_name": "萨摩亚"
    }, {
        "key": "1918",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Spain",
        "_firstCode": "X",
        "_mnemonic": "XBY",
        "_name": "西班牙"
    }, {
        "key": "2302",
        "_gArea": "35",
        "_gContinent": "3",
        "_nameGeo": "W. Sahara",
        "_firstCode": "X",
        "_mnemonic": "XSHL",
        "_name": "西撒哈拉"
    }, {
        "key": "0707",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Greece",
        "_firstCode": "X",
        "_mnemonic": "XL",
        "_name": "希腊"
    }, {
        "key": "0801",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "",
        "_firstCode": "X",
        "_mnemonic": "XG",
        "_name": "香港 [CN]"
    }, {
        "key": "1913",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Singapore",
        "_firstCode": "X",
        "_mnemonic": "XJP",
        "_name": "新加坡"
    }, {
        "key": "9702",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "New Caledonia",
        "_firstCode": "X",
        "_mnemonic": "XKLDNY",
        "_name": "新喀里多尼亚 [FR]"
    }, {
        "key": "1406",
        "_gArea": "41",
        "_gContinent": "4",
        "_nameGeo": "New Zealand",
        "_firstCode": "X",
        "_mnemonic": "XXL",
        "_name": "新西兰"
    }, {
        "key": "0805",
        "_gArea": "11",
        "_gContinent": "1",
        "_nameGeo": "Hungary",
        "_firstCode": "X",
        "_mnemonic": "XYL",
        "_name": "匈牙利"
    }, {
        "key": "1926",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Syria",
        "_firstCode": "X",
        "_mnemonic": "XLY",
        "_name": "叙利亚"
    }, {
        "key": "1001",
        "_gArea": "02",
        "_gContinent": "0",
        "_nameGeo": "Jamaica",
        "_firstCode": "Y",
        "_mnemonic": "YMJ",
        "_name": "牙买加"
    }, {
        "key": "0113",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Armenia",
        "_firstCode": "Y",
        "_mnemonic": "YMNY",
        "_name": "亚美尼亚"
    }, {
        "key": "2501",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Yemen",
        "_firstCode": "Y",
        "_mnemonic": "YM",
        "_name": "也门"
    }, {
        "key": "0908",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Iraq",
        "_firstCode": "Y",
        "_mnemonic": "YLK",
        "_name": "伊拉克"
    }, {
        "key": "0904",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "Iran",
        "_firstCode": "Y",
        "_mnemonic": "YL",
        "_name": "伊朗"
    }, {
        "key": "0906",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Israel",
        "_firstCode": "Y",
        "_mnemonic": "YSL",
        "_name": "以色列"
    }, {
        "key": "0907",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "Italy",
        "_firstCode": "Y",
        "_mnemonic": "YDL",
        "_name": "意大利"
    }, {
        "key": "0902",
        "_gArea": "22",
        "_gContinent": "2",
        "_nameGeo": "India",
        "_firstCode": "Y",
        "_mnemonic": "YD",
        "_name": "印度"
    }, {
        "key": "0903",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Indonesia",
        "_firstCode": "Y",
        "_mnemonic": "YDNXY",
        "_name": "印度尼西亚"
    }, {
        "key": "1103",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "United Kingdom",
        "_firstCode": "Y",
        "_mnemonic": "YG",
        "_name": "英国"
    }, {
        "key": "1003",
        "_gArea": "25",
        "_gContinent": "2",
        "_nameGeo": "Jordan",
        "_firstCode": "Y",
        "_mnemonic": "YD",
        "_name": "约旦"
    }, {
        "key": "2204",
        "_gArea": "23",
        "_gContinent": "2",
        "_nameGeo": "Vietnam",
        "_firstCode": "Y",
        "_mnemonic": "YN",
        "_name": "越南"
    }, {
        "key": "2601",
        "_gArea": "31",
        "_gContinent": "3",
        "_nameGeo": "Zambia",
        "_firstCode": "Z",
        "_mnemonic": "ZBY",
        "_name": "赞比亚"
    }, {
        "key": "9009",
        "_gArea": "14",
        "_gContinent": "1",
        "_nameGeo": "Jersey",
        "_firstCode": "Z",
        "_mnemonic": "ZXD",
        "_name": "泽西岛[GB]"
    }, {
        "key": "0323",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Chad",
        "_firstCode": "Z",
        "_mnemonic": "ZD",
        "_name": "乍得"
    }, {
        "key": "9006",
        "_gArea": "12",
        "_gContinent": "1",
        "_nameGeo": "",
        "_firstCode": "Z",
        "_mnemonic": "ZBLT",
        "_name": "直布罗陀 [GB]"
    }, {
        "key": "0310",
        "_gArea": "03",
        "_gContinent": "0",
        "_nameGeo": "Chile",
        "_firstCode": "Z",
        "_mnemonic": "ZL",
        "_name": "智利"
    }, {
        "key": "0308",
        "_gArea": "33",
        "_gContinent": "3",
        "_nameGeo": "Central African Rep.",
        "_firstCode": "Z",
        "_mnemonic": "ZFGHG",
        "_name": "中非共和国"
    }, {
        "key": "0301",
        "_gArea": "21",
        "_gContinent": "2",
        "_nameGeo": "China",
        "_firstCode": "Z",
        "_mnemonic": "ZG",
        "_name": "中国"
    }]

# 状态
V5Front_ResGPSSummary = [
    {
        "key": "00",
        "_iconBgColor": "757575",
        "_order": "01",
        "_name": "查询不到",
        "_tips": "您的包裹查询不到跟踪信息。"
    }, {
        "key": "10",
        "_iconBgColor": "2196f3",
        "_order": "02",
        "_name": "运输途中",
        "_tips": "您的包裹正在运输途中。"
    }, {
        "key": "20",
        "_iconBgColor": "b71c1c",
        "_order": "07",
        "_name": "运输过久",
        "_tips": "您的包裹已经运输了很长时间而仍未投递成功。"
    }, {
        "key": "30",
        "_iconBgColor": "0d47a1",
        "_order": "03",
        "_name": "到达待取",
        "_tips": "您的包裹已经可以收取。"
    }, {
        "key": "35",
        "_iconBgColor": "f44336",
        "_order": "04",
        "_name": "投递失败",
        "_tips": "您的包裹尝试派送但未能成功交付。"
    }, {
        "key": "40",
        "_iconBgColor": "43a047",
        "_order": "05",
        "_name": "成功签收",
        "_tips": "您的包裹已经成功签收。"
    }, {
        "key": "50",
        "_iconBgColor": "ff6f00",
        "_order": "06",
        "_name": "可能异常",
        "_tips": "您的包裹运输途中可能出现异常。"
    }
]

# 其他信息地图
V5Front_ResGISSummary = [
    {
        "key": "00",
        "_iconBgColor": "ff6f00",
        "_name": "无法跟踪",
        "_tips": "您所提交的单号无法跟踪。"
    }, {
        "key": "01",
        "_iconBgColor": "43a047",
        "_name": "查有信息",
        "_tips": "您所提交的单号已经查询到跟踪信息。"
    }, {
        "key": "02",
        "_iconBgColor": "9e9e9e",
        "_name": "查无信息",
        "_tips": "您所提交的单号查询不到跟踪信息。"
    }, {
        "key": "10",
        "_iconBgColor": "f44336",
        "_name": "网络错误",
        "_tips": "您所提交的单号访问出现了网络错误。"
    }, {
        "key": "11",
        "_iconBgColor": "f44336",
        "_name": "处理错误",
        "_tips": "您所提交的单号访问出现了处理错误。"
    }, {
        "key": "12",
        "_iconBgColor": "f44336",
        "_name": "查询错误",
        "_tips": "您所提交的单号访问出现了查询错误。"
    }
]
